[package]
name = "rust-rpg"
version = "0.1.0"
authors = ["George Popoff <popoff96@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
rodio = "0.11.0"